"""create partnerships and notifications tables

Revision ID: 0ec185b39531
Revises: 20f0f7c49a68
Create Date: 2026-09-18 09:20:47.068661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec185b39531'
down_revision: Union[str, Sequence[str], None] = '20f0f7c49a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountability_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('partner_habit_id', sa.Integer(), nullable=True),
    sa.Column('partner_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='partnership_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_habit_id'], ['habits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'partner_user_id')
    )
    op.create_index(op.f('ix_accountability_partners_habit_id'), 'accountability_partners', ['habit_id'], unique=False)
    op.create_index(op.f('ix_accountability_partners_partner_user_id'), 'accountability_partners', ['partner_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('STREAK_BROKEN', 'PARTNER_REQUEST', 'PARTNER_ACCEPTED', 'PARTNER_DECLINED', 'WAITING_FOR_PARTNER', 'GOAL_ACHIEVED', 'BADGE_EARNED', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('related_habit_id', sa.Integer(), nullable=True),
    sa.Column('related_partnership_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_habit_id'], ['habits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_partnership_id'], ['accountability_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_accountability_partners_partner_user_id'), table_name='accountability_partners')
    op.drop_index(op.f('ix_accountability_partners_habit_id'), table_name='accountability_partners')
    op.drop_table('accountability_partners')
    # ### end Alembic commands ###
