"""create shared goals table

Revision ID: 3d3d82c756c3
Revises: 0ec185b39531
Create Date: 2026-09-18 10:10:19.068468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3d82c756c3'
down_revision: Union[str, Sequence[str], None] = '0ec185b39531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partnership_id', sa.Integer(), nullable=False),
    sa.Column('target_streak_a', sa.Integer(), nullable=False),
    sa.Column('target_streak_b', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('reward_description', sa.String(length=500), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partnership_id'], ['accountability_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_goals_partnership_id'), 'shared_goals', ['partnership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_goals_partnership_id'), table_name='shared_goals')
    op.drop_table('shared_goals')
    # ### end Alembic commands ###
