"""create personal goals table

Revision ID: 423aefbd39cb
Revises: 9ed9998ed472
Create Date: 2026-09-20 14:01:54.793019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423aefbd39cb'
down_revision: Union[str, Sequence[str], None] = '9ed9998ed472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('target_days', sa.Integer(), nullable=True),
    sa.Column('reward_description', sa.String(length=500), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_goals_habit_id'), 'personal_goals', ['habit_id'], unique=False)
    op.create_index(op.f('ix_personal_goals_user_id'), 'personal_goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_goals_user_id'), table_name='personal_goals')
    op.drop_index(op.f('ix_personal_goals_habit_id'), table_name='personal_goals')
    op.drop_table('personal_goals')
    # ### end Alembic commands ###
