"""create badges tables

Revision ID: 862ce56f3f67
Revises: 3d3d82c756c3
Create Date: 2026-09-18 10:28:22.351881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862ce56f3f67'
down_revision: Union[str, Sequence[str], None] = '3d3d82c756c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('milestone_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_badges_milestone_days'), 'badges', ['milestone_days'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', 'habit_id')
    )
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the milestones every user can earn. Data lives in the migration so a
    # fresh database is usable straight after "alembic upgrade head".
    op.bulk_insert(
        sa.table(
            "badges",
            sa.column("code", sa.String),
            sa.column("title", sa.String),
            sa.column("milestone_days", sa.Integer),
        ),
        [
            {"code": "streak_3", "title": "Getting started", "milestone_days": 3},
            {"code": "streak_7", "title": "One week strong", "milestone_days": 7},
            {"code": "streak_14", "title": "Two weeks in", "milestone_days": 14},
            {"code": "streak_30", "title": "One month hero", "milestone_days": 30},
            {"code": "streak_100", "title": "Hundred days", "milestone_days": 100},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_badges_milestone_days'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
