"""add duck avatars and goal duration

Revision ID: 9ed9998ed472
Revises: 862ce56f3f67
Create Date: 2026-09-19 19:04:15.031425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed9998ed472'
down_revision: Union[str, Sequence[str], None] = '862ce56f3f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing goals predate the joint duration; give them a week so the column
    # can be NOT NULL without a separate backfill step.
    op.add_column(
        'shared_goals',
        sa.Column('duration_days', sa.Integer(), nullable=False, server_default='7'),
    )
    # add_column does not create the enum type itself, so do it first.
    duck_avatar = sa.Enum(
        'CLOVER', 'NERD', 'BOW', 'ADVENTURER', 'FOODIE', 'CHILL', name='duck_avatar'
    )
    duck_avatar.create(op.get_bind())
    op.add_column(
        'users',
        sa.Column('avatar', duck_avatar, server_default='CLOVER', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    sa.Enum(name='duck_avatar').drop(op.get_bind())
    op.drop_column('shared_goals', 'duration_days')
    # ### end Alembic commands ###
